# Automatically save the current playback position on quit
save-position-on-quit=yes
# Hide the window title bar and borders
no-border
# Completely hide the bottom on-screen controller (OSC) progress bar and timeline
script-opts=osc-visibility=never
# Keep window borders hidden
no-border
# SHOW the floating white bar when you rewind or skip
osd-bar=yes
osd-on-seek=bar

